# Generated by Django 4.2.1 on 2023-05-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
