# Generated by Django 4.2.1 on 2023-05-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_alter_office_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
