# Generated by Django 4.2.1 on 2023-05-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_office_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landload',
            name='logo',
            field=models.ImageField(upload_to='media/landloads'),
        ),
    ]
